-- ============================================================
-- Script 03: Data Exploration Queries
-- ============================================================
USE ZomatoDB;

-- 1. Count the number of restaurants in each city
SELECT city, COUNT(*) AS restaurant_count
FROM Zomato_Restaurants
GROUP BY city
ORDER BY restaurant_count DESC;

-- 2. Top 5 cities with the highest number of orders
SELECT r.city, COUNT(o.order_id) AS total_orders
FROM Zomato_Orders o
JOIN Zomato_Restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC
LIMIT 5;

-- 3. Total revenue generated by each restaurant
SELECT r.restaurant_id, r.restaurant_name, SUM(o.total_cost) AS total_revenue
FROM Zomato_Orders o
JOIN Zomato_Restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_revenue DESC;
